services:
    _defaults:
        public: true

    ##############
    # Your Module

    smartargetreviews.module:
        class: smartargetreviews
        factory: ['Module', 'getInstanceByName']
        arguments:
            - 'smartargetreviews'

    smartargetreviews.context:
        class: Context
        factory: ['Context', 'getContext']

    #####################
    # PrestaShop Account
    smartargetreviews.ps_accounts_installer:
        class: 'PrestaShop\PsAccountsInstaller\Installer\Installer'
        arguments:
            - '5.0'

    smartargetreviews.ps_accounts_facade:
        class: 'PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
        arguments:
            - '@smartargetreviews.ps_accounts_installer'

    #####################
    # PrestaShop Billing

    smartargetreviews.ps_billings_context_wrapper:
        class: 'PrestaShopCorp\Billing\Wrappers\BillingContextWrapper'
        arguments:
            - '@smartargetreviews.ps_accounts_facade'
            - '@smartargetreviews.context'
            - false # if true, enables the sandbox mode, if false or empty, disables it

    smartargetreviews.ps_billings_facade:
        class: 'PrestaShopCorp\Billing\Presenter\BillingPresenter'
        public: true
        arguments:
            - '@smartargetreviews.ps_billings_context_wrapper'
            - '@smartargetreviews.module'

    # Remove this if you do not need BillingService
    smartargetreviews.ps_billings_service:
        class: 'PrestaShopCorp\Billing\Services\BillingService'
        public: true
        arguments:
            - '@smartargetreviews.ps_billings_context_wrapper'
            - '@smartargetreviews.module'
